### ISSUE TITLE
Uncaught TypeError: m.easing[this.easing] is not a function

### ISSUE THREAD

**Issue by cesasol** [frenski/quizy-memorygame#12]
When using this plugin, after click two cards it just stop working and the console shows:
Uncaught TypeError: m.easing[this.easing] is not a function
Searching for a solution I found out that there is a incompability with newer versions of Jquery.

How could I workaround this?

**Comment by frenski** [comment]
Hi @cesasol,

It might come from some incompatibility between the jquery and jquery UI. What versions of the libraries are you using?

Possible solutions would be:
1. Use jquery and jquery UI libs that are both compatible with each other and compatible with the dependency plugin flip.js (I think everything below version 2 should be OK, but you've gotta try)
2. Remove flip.js and jquery UI libs. The only place where UI is required is for the flipping effect of the cards. It uses a very old library called flip.js (it was used back then, since I wanted to make sure the effect works on very old browsers too). But that, you will have to rely on the scroll or the fade effects.
3. Wait a bit for me to update the plugin to work with CSS3 instead of using flip.js with jQuery UI (It won't happen before the end of the month though, since I am over busy by then  :( )

**Comment by cesasol** [comment]
Thanks!, the problem was the dependency for flip.js. Sorry for bothering you

**Comment by frenski** [comment]
No problem. I'll remove soon the flip.js dependency and will replace the effect with CSS3.
